### ISSUE TITLE
Search 2.0

### ISSUE THREAD

**Issue by deevroman** [deevroman/better-osm-org#89]
- [ ] Filter by object type
- [ ] Improve default zoom
- [ ] Photon?
- [ ] Overpass?
- [ ] search.bbbike.org ?

**Comment by deevroman** [comment]
https://github.com/user-attachments/assets/15402856-859f-4d5a-bf3f-741502eb58ae

via. https://t.me/urban_science/491

**Comment by deevroman** [comment]
Replace country name to emoji
